### PR TITLE
All 49 occurences of the code snippet .collect(Collectors.toList()) changed to .toList() in all of the 17 files.

### PR DESCRIPTION
**Pull request by nagendra0446**
Fixes as a part of issue #15.
Total of **49 occurrences** of the code snippet **.collect(Collectors.toList())** changed to **.toList()** in total of **17 files**.

### CODE REVIEW

**Comment by JCWasmx86** [comment]
Thanks for your contribution! As you can see, the CI builds fail.
Some remarks:
-The CI builds currently use Java 15 and `toList()` is only available since Java 16.
-`toList()` may return an unmodifiable list, so not all `.collect(Collectors.toList())` can be replaced.

**Comment by JCWasmx86** [comment]
May I add you to the contributors-section in the Game? (E.g. a link to your github page)

**Comment by nagendra0446** [comment]
No problem and I will continue to contribute the repository.

**Comment by JCWasmx86** [comment]
Done! That's really nice to hear! Do you need any guidance? Or ideas for tasks?

**Comment by nagendra0446** [comment]
No problem and I will continue to contribute to the repository.

**Comment by nagendra0446** [comment]
I am currently learning and trying to contribute and in case of any doubts
or help, I will ping you, Sir. By the way, may I know your good name, Sir?
I am Nagendra Nainala, a CSE undergraduate from JNTUH CES India and
passionate about software development, Machine Learning, and many other
technologies.

**Comment by JCWasmx86** [comment]
>I am currently learning and trying to contribute and in case of any doubts
or help, I will ping you, Sir.

Sure

>By the way, may I know your good name, Sir?

I'm really don't want my name in the internet.

**Comment by nagendra0446** [comment]
Oh!

**Pull request merged**
